# Legacy KF board: V0, V1 (V2 is the same as V1), V3 is latest and deployed in default directory
dtb-$(CONFIG_ARCH_R8A7795) += r8a7795-es1-h3ulcb-kf-v0.dtb r8a7795-es1-h3ulcb-kf-v1.dtb
dtb-$(CONFIG_ARCH_R8A7796) += r8a7796-m3ulcb-kf-v0.dtb r8a7796-m3ulcb-kf-v1.dtb
dtb-$(CONFIG_ARCH_R8A7795) += r8a7795-h3ulcb-kf-v0.dtb r8a7795-h3ulcb-kf-v1.dtb
dtb-$(CONFIG_ARCH_R8A7797) += r8a7797-v3msk-kf-v0.dtb

always		:= $(dtb-y)
clean-files	:= *.dtb
